version: "3.9"
services:
  broker:
    image: rabbitmq:3.10-management
    ports:
      - 5672:5672
      - 15672:15672
    hostname: broker

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    hostname: db
    environment:
      POSTGRES_PASSWORD: Dhanush97
      POSTGRES_USER: sanju

  dictator:
    build:
      context: dictator/
    ports:
      - 3000:3000