apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcm-deployment-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcm
  template:
    metadata:
      labels:
        app: dcm
    spec:
      containers:
      - name: broker
        image: rabbitmq:3.10-management
        ports:
        - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  selector:
    app: dcm
  ports:
  - name: http
    port: 5672
    targetPort: 5672
  type: ClusterIP


